baseURL: "https://luegm.dev"
languageCode: en-us
title: LuegM ðŸ‘¨ðŸ»â€ðŸ’»
paginate: 5
theme: ["hugo-notice", "PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

params:
  defaultTheme: auto
  DateFormat: "02.01.2006"
  homeInfoParams:
    Title: "Hi there, I'm Michael \U0001F44B"
    Content: >
        Welcome to my blog.
        I am a software developer focusing on iOS app development.

        Here you can find my socials and contact details:

  socialIcons:
      - name: mail
        url: "mailto:me@luegm.dev"
      - name: github
        url: "http://github.com/luegm"
      - name: twitter
        url: "https://twitter.com/lueg_m"
      - name: linkedin
        url: "https://www.linkedin.com/in/luegm/"
      - name: "rss"
        url: "https://luegm.dev/index.xml"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true

  ShowPostNavLinks: true
  ShowShareButtons: true

  ShowCodeCopyButtons: true
  ShowToc: true
  ShowFullTextinRSS: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary